export const destinations = [
  {
    id: 1,
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    budget: "Luxury",
    rating: 4.9,
    price: 1450,
    days: "5 Days",
    tags: ["Beach", "Romantic", "Sunset"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    description:
      "Whitewashed cliffside villages, volcanic beaches, and the most iconic sunsets in the Aegean Sea. Santorini blends dramatic scenery with world-class wine and seafood.",
  },
  {
    id: 2,
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    budget: "Mid-range",
    rating: 4.8,
    price: 980,
    days: "6 Days",
    tags: ["Culture", "Temples", "Nature"],
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    description:
      "Thousands of Buddhist temples, serene bamboo groves, and geisha-lined streets. Kyoto is Japan's cultural heart, especially magical during cherry blossom season.",
  },
  {
    id: 3,
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    budget: "Mid-range",
    rating: 4.9,
    price: 1120,
    days: "7 Days",
    tags: ["Adventure", "Hiking", "History"],
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    description:
      "An ancient Incan citadel perched high in the Andes. Trek the legendary trail or take the scenic train through breathtaking cloud-forest landscapes.",
  },
  {
    id: 4,
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    budget: "Budget",
    rating: 4.7,
    price: 650,
    days: "8 Days",
    tags: ["Beach", "Nature", "Wellness"],
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    description:
      "Lush rice terraces, ancient temples, and world-famous surf breaks. Bali offers everything from beach parties to quiet yoga retreats.",
  },
  {
    id: 5,
    name: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    budget: "Luxury",
    rating: 4.8,
    price: 1780,
    days: "6 Days",
    tags: ["Nature", "Adventure", "Northern Lights"],
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80",
    description:
      "Glaciers, geysers, and the Northern Lights dancing overhead. Iceland's otherworldly landscapes make it a bucket-list destination for adventurers.",
  },
  {
    id: 6,
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    budget: "Budget",
    rating: 4.6,
    price: 590,
    days: "5 Days",
    tags: ["Culture", "Market", "History"],
    image: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80",
    description:
      "A sensory feast of bustling souks, ornate riads, and the Atlas Mountains on the horizon. Marrakech is vibrant, chaotic, and endlessly photogenic.",
  },
  {
    id: 7,
    name: "Banff",
    country: "Canada",
    region: "North America",
    budget: "Mid-range",
    rating: 4.9,
    price: 1340,
    days: "6 Days",
    tags: ["Nature", "Hiking", "Lakes"],
    image: "https://images.unsplash.com/photo-1609825488888-3a766db05542?w=800&q=80",
    description:
      "Turquoise glacial lakes framed by snow-capped Rockies. Banff National Park is a paradise for hikers, photographers, and wildlife lovers.",
  },
  {
    id: 8,
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    budget: "Luxury",
    rating: 4.8,
    price: 1600,
    days: "7 Days",
    tags: ["Adventure", "Nature", "Sports"],
    image: "https://images.unsplash.com/photo-1589871173980-5c353e5f4b0e?w=800&q=80",
    description:
      "The adventure capital of the world — bungee jumping, jet boating, and epic hiking trails set against dramatic alpine scenery.",
  },
  {
    id: 9,
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    budget: "Mid-range",
    rating: 4.7,
    price: 890,
    days: "6 Days",
    tags: ["Beach", "Nature", "Wildlife"],
    image: "https://images.unsplash.com/photo-1580060839134-75a50c0cea78?w=800&q=80",
    description:
      "Table Mountain, penguin-dotted beaches, and world-class vineyards all in one city. Cape Town pairs urban culture with raw natural beauty.",
  },
];

export const regions = ["All", "Europe", "Asia", "South America", "North America", "Africa", "Oceania"];
export const budgets = ["All", "Budget", "Mid-range", "Luxury"];
